apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: team-a
  name: team-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-a-app
  namespace: team-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: team-a-app
  template:
    metadata:
      labels:
        app: team-a-app
    spec:
      containers:
      - name: hello-kubernetes
        image: liorkamrat/hello-arc:latest
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: This is Team A Application deployed via Azure Arc!
---
apiVersion: v1
kind: Service
metadata:
  name: team-a-app
  namespace: team-a
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: team-a-app
